"""created StripeProduct model

Revision ID: f483d00d3db3
Revises: beb759b444f3
Create Date: 2021-07-13 12:39:01.471886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f483d00d3db3'
down_revision = 'beb759b444f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product', sa.String(), nullable=False))
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_id')
    op.add_column('stripe_product', sa.Column('stripe_product_id', sa.String(), nullable=True))
    op.add_column('stripe_product', sa.Column('tax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_product', 'tax')
    op.drop_column('stripe_product', 'stripe_product_id')
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'product', ['product_id'], ['id'])
    op.drop_column('cart', 'product')
    # ### end Alembic commands ###
